#INCLUDE "rwmake.ch"
#INCLUDE "topconn.ch"

//------------------------------------------------------------------------------
/*{Protheus.doc} ADV001
Rotina para montagem da tela de técnico do Axcadastro

@author 	Rogerio Onishi Candisani
@version 	P12
@since   	
*/
//------------------------------------------------------------------------------
User Function ADV001()

AxCadastro("ZZA","Cadastro de Tecnicos")

Return
