#INCLUDE "rwmake.ch"
#INCLUDE "topconn.ch"

//------------------------------------------------------------------------------
/*{Protheus.doc} ADV003
Rotina para montagem da tela de tipos de chamados de axCadastro

@author 	Rogerio Onishi Candisani
@version 	P12
@since   	
*/
//------------------------------------------------------------------------------
User Function ADV003()

AxCadastro("ZZC","Cadastro de Tipos de Chamados")

Return